# name: Node.js CI

on:
  - push
  - pull_request

jobs:
  build-app:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with: { version: 7 }

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      # install deps
      - run: pnpm install

      # test
      - run: pnpm test-cover

      - uses: codecov/codecov-action@v3
